services:
    bot:
        build:
            context: .
            dockerfile: dockerfile/bot.dockerfile
        image: cgeeb8765/discorder-bot
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./data:/app/data
        network_mode: host
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - whisper

    whisper:
        build:
            context: .
            dockerfile: dockerfile/whisper.dockerfile
        image: cgeeb8765/discorder-whisper
        env_file:
            - .env
        restart: always
        ports:
            - 38080:38080
